### ISSUE TITLE
Missing icon for forget messages

### ISSUE THREAD

**Issue by leirbag95** [aleph-im/aleph-explorer#54]
When a message is forgotten, an icon or title is missing which indicates that it is a forgotten message such as "**Aggregate**" or "**Store messages**" in the "General Dashboard" or "Messages" section.

See the following image:

![screenshot](https://user-images.githubusercontent.com/17054452/206502507-c85b32db-3060-4825-839c-9d4845585531.png)

**Comment by BjrInt** [comment]
fixed in #59
