### ISSUE TITLE
Null post crashes the view

### ISSUE THREAD

**Issue by lgaroche** [aleph-im/aleph-explorer#88]
I created a null post using the aleph post command (type `null` when prompted for the content). 
It created a [post](https://explorer.aleph.im/address/ETH/0x5Ac1D60E8766c42d3718E831A7b43B3370F6504D/message/POST/f2b0c64a58f75a867b59059660af92a52ccd299df892c9b794036e5245e56430) with an `undefined` content. 

In the message list, this causes an error and the list is not loaded, see [this search link](https://explorer.aleph.im/messages?showAdvancedFilters=1&channels=TEST&type=POST&page=1&sender=0x5Ac1D60E8766c42d3718E831A7b43B3370F6504D).

The error comes from this line, where `JSON.stringify(undefined)` is `undefined`
https://github.com/aleph-im/aleph-explorer/blob/master/src/components/MessageList.vue#L74

**Comment by nesitor** [comment]
Fixed on https://github.com/aleph-im/aleph-explorer/pull/89 pull request.
